-- MySQL Script generated by MySQL Workbench
-- Wed Nov 13 19:25:24 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL,
  `datacontratacao` DATE NULL,
  PRIMARY KEY (`idfuncionarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedores` (
  `idfornecedores` INT NOT NULL,
  `nome` VARCHAR(60) NULL,
  `endereco` VARCHAR(60) NULL,
  `cidade` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idfornecedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`livros` (
  `idlivros` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `anopublicacao` YEAR NULL,
  `edicao` INT NULL,
  `editora` VARCHAR(60) NULL,
  `fornecedores_idfornecedores` INT NOT NULL,
  PRIMARY KEY (`idlivros`),
  INDEX `fk_livros_fornecedores_idx` (`fornecedores_idfornecedores` ASC),
  CONSTRAINT `fk_livros_fornecedores`
    FOREIGN KEY (`fornecedores_idfornecedores`)
    REFERENCES `mydb`.`fornecedores` (`idfornecedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoques` (
  `idestoques` INT NOT NULL AUTO_INCREMENT,
  `quant_total` INT NULL,
  `quat_recebida` INT NULL,
  `dataatualizacao` DATE NULL,
  `livros_idlivros` INT NOT NULL,
  `funcionarios_idfuncionarios` INT NOT NULL,
  PRIMARY KEY (`idestoques`),
  INDEX `fk_estoques_livros1_idx` (`livros_idlivros` ASC),
  INDEX `fk_estoques_funcionarios1_idx` (`funcionarios_idfuncionarios` ASC),
  CONSTRAINT `fk_estoques_livros1`
    FOREIGN KEY (`livros_idlivros`)
    REFERENCES `mydb`.`livros` (`idlivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estoques_funcionarios1`
    FOREIGN KEY (`funcionarios_idfuncionarios`)
    REFERENCES `mydb`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
